export const TOP_MENU_HEIGHT = 42
export const TOP_MENU_THRESHOLD = 10

export const CANVAS_KEY = 'CANVAS_KEY'
export const CANVAS_DRAW_CONTAINER_KEY = 'CANVAS_DRAW_CONTAINER_KEY'
export const CANVAS_DRAW_DRAG_ELEMENT_KEY = 'CANVAS_DRAW_DRAG_ELEMENT_KEY'
